version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=weather_user
      - POSTGRES_PASSWORD=weather
      - POSTGRES_DB=weather
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: ./react
      target: development
    volumes:
      - ./react/src:/app/src
    ports:
      - "127.0.0.1:3000:3000"
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://weather_user:weather@db/weather
    volumes:
      - ./app:/code/app
    ports:
      - "127.0.0.1:8008:80"

volumes:
  postgres_data: